- name: terminate the ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0f45cd6cf89edb6b8
    ami_id: ami-0220d79f3f480ecf5
    domain_name: ssrdevops.online
    env: dev
    action: destroy
    instances:
    - mongodb
    - catalogue
  tasks:

  - name: delete r53 records for frontend
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when:
    - item == "frontend"
    - action == "destroy"

  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}-{{ env }}"
      wait: false
    loop: "{{ instances }}"
    when: action == "destroy"
      